### PR TITLE
[tests-only] add public storage tests

### PR DESCRIPTION
**Pull request by wkloucek**
This PR adds:
- tooling to generate mocks from an interface. Mockery was already used in some go:generate directives, but depended on a local installation. Now it will be automatically installed when running go generate. Also CI now checks, that generated mocks are up to date and not altered.
- tests for the public  share storage provider
- tests for the public share authentication
- tests for the public share scope checker

### CODE REVIEW

**Comment by micbar** [comment]
some markdown is failing the Codacy linter. 

Integration Tests are looking good so far.

**Comment by wkloucek** [comment]
@ishank011 can you please have a look at this?

**Comment by micbar** [comment]
@ishank011 @labkode this is ready to be merged IMO, tests

**Comment by wkloucek** [comment]
This already has bit rotted. Created another PR for the mockery changes https://github.com/cs3org/reva/pull/2671

**Pull request closed without merging**
