### PR TITLE
fixed the response code when copying the file from shares to personal space

### PR DESCRIPTION
**Pull request by 2403905**
Related Issue [#9482](https://github.com/owncloud/ocis/issues/9482)

### CODE REVIEW

**Review by fschade — APPROVED** [review]
LGTM, one thing, since there was no red ci, i expect we have not tested this code path in the past... could you add some tests for ` httpDownloadRes.StatusCode == http.StatusForbidden`.

just in case, why do you return nil instead of the err?

THANKS 🤗

**Comment by phil-davis** [comment]
From an API test point-of-view, I think test coverage is related to issue https://github.com/owncloud/ocis/issues/8428
API tests have not been added yet for this case. And I think that we have been asked not to add test scenarios that fail (for example, due to a known reported bug like this). So there won't be an API test scenario that starts passing.

To verify the fix at the API level, someone would need to add a test scenario to the ocis API tests, then make that test run here (an extra PR from here that uses the new branch in ocis as the source for the tests).

But maybe you are just referring to unit tests? @fschade I am not sure what level of test you mean.

**Comment by fschade** [comment]
> From an API test point-of-view, I think test coverage is related to issue [owncloud/ocis#8428](https://github.com/owncloud/ocis/issues/8428) API tests have not been added yet for this case. And I think that we have been asked not to add test scenarios that fail (for example, due to a known reported bug like this). So there won't be an API test scenario that starts passing.
> 
> To verify the fix at the API level, someone would need to add a test scenario to the ocis API tests, then make that test run here (an extra PR from here that uses the new branch in ocis as the source for the tests).
> 
> But maybe you are just referring to unit tests? @fschade I am not sure what level of test you mean.

Yes exactly, not a logic test, more like a behavior test :)
thanks for the detailed explanation

**Comment by saw-jan** [comment]
We have a PR #9437 to cover the behavior but not merged because it was not fixed yet. We will test and report if the fixes worked with the new test scenarios.

**Comment by saw-jan** [comment]
Also, we do not have secure-view role test scenarios in `coreApi` tests (test suites running for reva). Secure view tests only runs in ocis ci because we do not run ocis api test suites in reva.

**Comment by 2403905** [comment]
> LGTM, one thing, since there was no red ci, i expect we have not tested this code path in the past... could you add some tests for ` httpDownloadRes.StatusCode == http.StatusForbidden`.
> 
> just in case, why do you return nil instead of the err?
> 
> THANKS 🤗

We return the nil because the error will be handled as a 500

**Pull request merged**
