### PR TITLE
Implement OCM protocol

### PR DESCRIPTION
**Pull request by ishank011**
Migrating the OCM service from https://github.com/cernbox/ocmd to reva. Still a work in progress.

### CODE REVIEW

**Comment by labkode** [comment]
@ishank011 @JarCz what is the status of this PR? I propose we merge what is already here and add missing functionality later on.

**Comment by ishank011** [comment]
@labkode from my side, the initial changes are complete. There are a few linting issues in @JarCz's code, and he is rewriting the share manager memory driver. So once that is done, I guess we can merge it

**Comment by labkode** [comment]
@ishank011 thanks, @JarCz what was the problem with the current memory manager?

**Comment by ishank011** [comment]
@labkode he was fixing issues in the OCM share manager that we wrote.

**Comment by JarCz** [comment]
@labkode I'm rewrite memory drive and wait to merage my changes with @ishank011

**Pull request merged**
