### PR TITLE
Migrate ocisIntegrationTests and s3ngIntegrationTests to GitHub Actions

### PR DESCRIPTION
**Pull request by vascoguita**

### CODE REVIEW

**Comment by phil-davis** [comment]
https://github.com/cs3org/reva/actions/runs/4085928053/jobs/7044608957
"This step has been truncated due to its large size."

I guess that docker-compose is starting up the reva system-under-test and the test runner (behat...), but the system-under-test is spewing out large amounts of "log" output. Can that be cut down? Or the output redirected to `/dev/null` ? Or something.

Maybe then we will be able to see `ocis/tests/acceptance/run.sh` be executed, and `behat` start etc.

**Comment by vascoguita** [comment]
> https://github.com/cs3org/reva/actions/runs/4085928053/jobs/7044608957 "This step has been truncated due to its large size."
> 
> I guess that docker-compose is starting up the reva system-under-test and the test runner (behat...), but the system-under-test is spewing out large amounts of "log" output. Can that be cut down? Or the output redirected to `/dev/null` ? Or something.
> 
> Maybe then we will be able to see `ocis/tests/acceptance/run.sh` be executed, and `behat` start etc.

Sure, my latest commit should do it.

**Comment by vascoguita** [comment]
> https://github.com/cs3org/reva/actions/runs/4085928053/jobs/7044608957 "This step has been truncated due to its large size."
> 
> I guess that docker-compose is starting up the reva system-under-test and the test runner (behat...), but the system-under-test is spewing out large amounts of "log" output. Can that be cut down? Or the output redirected to `/dev/null` ? Or something.
> 
> Maybe then we will be able to see `ocis/tests/acceptance/run.sh` be executed, and `behat` start etc.

@phil-davis The output of the system-under-test has been suppressed and now we're able to see the output of `ocis/tests/acceptance/run.sh`: https://github.com/cs3org/reva/actions/runs/4125226916
Could you help us understand debug the tests please?

**Comment by phil-davis** [comment]
Now it needs a rebase and resolve conflicts in `.drone.env`

The CI runs from last week do not have many unexpected failures. (from comment https://github.com/cs3org/reva/pull/3640#issuecomment-1425554546 ) But somehow the rendering in the GitHub workflow output is very hard to read.

Do the rebase and I will look again.

Maybe I will need to get rid of the fancy colour output strings, which GitHub log output is not interpreting. That will make things easier to read.

**Comment by phil-davis** [comment]
See https://github.com/cs3org/reva/pull/3672 - that works with the acceptance tests and the current drone scripts. The acceptance test output comes as plain text, without any escape sequence to select text colors etc.

If you rebase this PR, and set env variable `PLAIN_OUTPUT` in the workflows, then we should get a much cleaner output that we can read more easily and then look at why some tests are failing.

**Comment by vascoguita** [comment]
> See #3672 - that works with the acceptance tests and the current drone scripts. The acceptance test output comes as plain text, without any escape sequence to select text colors etc.
> 
> If you rebase this PR, and set env variable `PLAIN_OUTPUT` in the workflows, then we should get a much cleaner output that we can read more easily and then look at why some tests are failing.

Thanks Phil, PLAIN_OUTPUT is set now but errors on the run.sh script are causing the tests to fail. I see that you've fixed the variable assignments (https://github.com/owncloud/ocis/pull/5624) and tried to bump ocis on reva (#3680 ) but it's failing Drone. I'll rebase and re-run GitHub Actions after it's fixed.

**Comment by phil-davis** [comment]
There is also #3679 waiting for approval and merge. After that is merged, I will stop changing test code! And we can concentrate on what failures remain.

**Comment by vascoguita** [comment]
> There is also #3679 waiting for approval and merge. After that is merged, I will stop changing test code! And we can concentrate on what failures remain.

Thanks @phil-davis , #3679 is now merged. Me and @labkode found that some tests were failing on Alma8 self-hosted runners so we upgraded the cluster used by my fork (only https://github.com/vascoguita/reva so far) to Alma9 but there are other tests failing.

**Pull request merged**
