### PR TITLE
[tests-only] Bump test suite

### PR DESCRIPTION
**Pull request by aduffeck**

### CODE REVIEW

**Comment by phil-davis** [comment]
@aduffeck there are other changes that will be needed to expected-failures line numbers.
See https://github.com/cs3org/reva/pull/3872/files

Should we adjust that PR, or you keep going with this one?

**Comment by aduffeck** [comment]
@phil-davis sorry, just saw your comment now. I tried to cherry-pick that commit and then bump to current master which now has a few more changes to the tests. I hope it'll be fine now :|

**Comment by aduffeck** [comment]
@phil-davis alright, it didn't work out. Do you think it would make more sense to move forward with your PR?

**Comment by phil-davis** [comment]
Yes, I know what other things happened with test scenarios in ocis master. I will adjust the other PR

**Comment by aduffeck** [comment]
Awesome, thanks a lot.

**Pull request closed without merging**
