### PR TITLE
[tests-only][full-ci] Bump ocis commit id for tests 

### PR DESCRIPTION
**Pull request by S-Panta**
This PR bumps ocis commit id for tests
Part of: https://github.com/owncloud/QA/issues/815

### CODE REVIEW

**Comment by saw-jan** [comment]
Another PR to bump ocis: https://github.com/cs3org/reva/pull/4013. Same failures

**Comment by micbar** [comment]
@saw-jan Could it be, that we should not use the spaceContext in reva at all?

**Comment by saw-jan** [comment]
> @saw-jan Could it be, that we should not use the spaceContext in reva at all?

Yeah, I think the hooks got loaded from one of the PRs in oCIS ( (I think in https://github.com/owncloud/ocis/pull/6627))
Will push the fix to the oCIS repo

**Comment by S-Panta** [comment]
The bump is done in PR https://github.com/cs3org/reva/pull/4013, so closing this.

**Pull request closed without merging**
