### PR TITLE
[tests-only] Bump commit id for API tests

### PR DESCRIPTION
**Pull request by phil-davis**
Gets us:
https://github.com/owncloud/core/pull/38184 [tests-only] low level TUS tests for uploading chunks

### CODE REVIEW

**Comment by phil-davis** [comment]
@labkode @ishank011 there is no drone CI happening any more.
What happened?

**Comment by phil-davis** [comment]
Question about drone has been asked at https://discourse.drone.io/t/new-builds-not-appearing-on-drone/8479

Waiting for news...

**Comment by labkode** [comment]
@phil-davis is this still needed? In case, can you submit another PR to trigger the CI?

**Comment by phil-davis** [comment]
This is old - superseded by  #1372 which is already merged.

**Pull request closed without merging**
