### PR TITLE
remove fmt.Print statement from decomposedfs

### PR DESCRIPTION
**Pull request by wkloucek**
fixes https://github.com/owncloud/ocis/issues/2290

### CODE REVIEW

**Comment by wkloucek** [comment]
@butonic what should we do here? There is no logging available. Can we just remove the Print statements?

**Comment by butonic** [comment]
The correct implementation would check
1. if the symlink already exists
2. if it points to the correct node (if not overwrite the existing symlink)
3. if the symlink cannot be created ... log an error ... hah the trick is https://github.com/cs3org/reva/blob/b1d57b9313d743e3afdf0490b93c6f45e57559d0/pkg/auth/manager/ldap/ldap.go#L113

it will use the default log configuration, but at least it is a structured log message.

and the left over case really is an error the admin should tackle, because the correct symlink cannot be created.

**Comment by wkloucek** [comment]
> The correct implementation would check
> 
> 1. if the symlink already exists
> 2. if it points to the correct node (if not overwrite the existing symlink)
> 3. if the symlink cannot be created ... log an error ... hah the trick is https://github.com/cs3org/reva/blob/b1d57b9313d743e3afdf0490b93c6f45e57559d0/pkg/auth/manager/ldap/ldap.go#L113
> 
> it will use the default log configuration, but at least it is a structured log message.
> 
> and the left over case really is an error the admin should tackle, because the correct symlink cannot be created.

Doesn't sound like just replacing the Print with a Log. Could you please take care?

**Comment by butonic** [comment]
closing in favor of https://github.com/cs3org/reva/pull/1992

**Pull request closed without merging**
