### PR TITLE
Added a CS3API compliant data exporter to Mentix

### PR DESCRIPTION
**Pull request by Daniel-WWU-IT**
A new HTTP endpoint has been added that exports data in a format compliant to the CS3API `ProviderInfo` structure.

### CODE REVIEW

**Comment by labkode** [comment]
@Daniel-WWU-IT some hound linting

**Comment by ishank011** [comment]
@Daniel-WWU-IT you can just use small-case for the first letter for internal methods. Saves you from adding comments.

**Comment by Daniel-WWU-IT** [comment]
> @Daniel-WWU-IT you can just use small-case for the first letter for internal methods. Saves you from adding comments.
They aren't internal, otherwise I would have done so. I add comments to types and functions where it makes sense, not just to make the hound happy ;) And these are not the only exported funcs/types that lack comments.

**Comment by ishank011** [comment]
Ideally, all the exported methods should have comments, even though they are self-explanatory ;)
Could you point me to those which aren't commented? I might as well fix those.

**Comment by Daniel-WWU-IT** [comment]
> Ideally, all the exported methods should have comments, even though they are self-explanatory ;)
> Could you point me to those which aren't commented? I might as well fix those.

I think I stumbled upon a few in some other services, not sure if this has changed yet. But I'll go through my code and comment all the obvious ;)

**Comment by Daniel-WWU-IT** [comment]
Comments added... hope I got all places

**Comment by ishank011** [comment]
Awesome! Thanks!

**Pull request merged**
