### PR TITLE
Retry trashbin in case of timestamp collision

### PR DESCRIPTION
**Pull request by PVince81**
In OC storage the file name pattern for deleted files include the
timestamp: "deleted.d12345678". In some rare cases like when running
tests, it can happen that the deletion happens so fast that it causes
timestamp collisions for the same file names.

To fix this, if we detect the collision case we retry again with a
higher timestamp value.

After this, the Webdav Litmus test cleanup routine works correctly.

Fixes https://github.com/owncloud/ocis-reva/issues/184

Also see: https://github.com/owncloud/core/issues/23151

### CODE REVIEW

**Comment by labkode** [comment]
@PVince81  perhaps a nano second resolution will work?

**Comment by PVince81** [comment]
Yeah, but here I'm assuming that we want to keep the same old file name schema to stay compatibleAm 08.05.2020 13:36 schrieb "Hugo G. Labrador" <notifications@github.com>:
@PVince81  perhaps a nano second resolution will work?

**Comment by PVince81** [comment]
looks like I have some leftover debug code here, will remove

**Comment by PVince81** [comment]
I've removed the debug code.

**Pull request merged**
