### PR TITLE
Range request attempt WIP

### PR DESCRIPTION
**Pull request by PVince81**
Naive draft attempt at adding range request.
This would require the underlying data provider + storage to support range headers.

Strangely when I run this it doesn't return the "Accept-range" request.

For https://github.com/owncloud/ocis-reva/issues/12

@butonic FYI

### CODE REVIEW

**Comment by PVince81** [comment]
Ok, I missed changing my go.mod with the replace...

So the HEAD call returns the headers.

The GET call returns the full content, which is expected because the underlying layers likely don't support the range headers yet

**Comment by PVince81** [comment]
Actually the "HEAD" request should also ping the backend to find out if it "accepts ranges"...

**Comment by PVince81** [comment]
seems we might need the CS3 APIs to support range requests: https://github.com/owncloud/ocis-reva/issues/12

**Comment by labkode** [comment]
@PVince81 I think we can add them to CS3APIS at some point, however what if we try the following for time being:

```
1) Get with Range header arrives to ocdav layer
2) ocdav will call CS3APIS:InitiateFileUpload and get the TUS server address
3) ocdav will send Range header to TUS data server
4) TUS data server will serve only the requested bytes
```

**Comment by PVince81** [comment]
now that I'm a bit more familiar, maybe passing this through the Opaque would be enough ?

**Comment by PVince81** [comment]
never mind, I just saw your proposal, doing a range request to the data provider sounds like a better approach

**Pull request closed without merging**
