### PR TITLE
Merge nextcloud-alpha into edge

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
I'll work out the hound errors and there are also a few tests that need to be adapted to recent evolution of the APIs between Reva and Nextcloud.

**Comment by butonic** [comment]
Happy new new year! @michielbdejong 
Most of the ocis team is back from vacation, so ping us when you think this is ready. Looking forward to it!

**Comment by michielbdejong** [comment]
@butonic Thanks! I think the tests are passing now (still waiting for a few unrelated integration tests to finish).

**Review by butonic — APPROVED** [review]
nice job!

**Comment by michielbdejong** [comment]
Thanks! :)

**Pull request merged**
