### PR TITLE
Posixfs trashbin

### PR DESCRIPTION
**Pull request by aduffeck**
Implement trashbin functionality for posixfs

### CODE REVIEW

**Comment by butonic** [comment]
When I delete a file the trishbin shows the deletion time as 1h in the future...

**Comment by butonic** [comment]
I tried restoring a folder with children
grafik

**Comment by butonic** [comment]
even after refreshing I still see foo twice ... hm ... but on disk the folder seems fine:
```
➜  reva git:(posixfs-trashbin) ls -lah /home/jfd/tmp/posix-storage/users/admin/       
insgesamt 36K
drwxr-x--- 5 jfd jfd 4,0K 26. Aug 13:17  .
drwxr-xr-x 3 jfd jfd 4,0K 26. Aug 13:17  ..
drwxr-xr-x 3 jfd jfd 4,0K 26. Aug 12:35  foo
drwx------ 2 jfd jfd 4,0K 26. Aug 12:29 'New folder'
drwxr-xr-x 4 jfd jfd 4,0K 26. Aug 13:16  .Trash
```

**Comment by butonic** [comment]
reproducer:
1. create /foo/bar/bif/123.txt (i did that on the cli)
2. trash /foo
3. restore /foo from the trash
4. list / -> see foo 4 times

**Comment by aduffeck** [comment]
@butonic hm, do you mind sharing your config? I can not reproduce the issue both with personal and projects spaces.

**Comment by butonic** [comment]
my config:
```json

			{
				"name": "cloud.ocis.test posix",
				"type": "go",
				"request": "launch",
				//"buildFlags": "-race",
				"mode": "debug",
				"program": "${workspaceFolder:ocis}/ocis/cmd/ocis",
				"args": [ "server" ],
				"env": {
					// set insecure options because we don't have valid certificates in dev environments
					"OCIS_INSECURE": "true",
					// enable basic auth for dev setup so that we can use curl for testing
					"PROXY_ENABLE_BASIC_AUTH": "true",
					
					"OCIS_URL": "https://cloud.ocis.test",
					"OCIS_LOG_LEVEL": "error",
					"OCIS_LOG_PRETTY": "true",
					"OCIS_LOG_COLOR": "true",
					"NATS_LOG_LEVEL": "error",
			  	  
					
					// setup as per https://owncloud.dev/architecture/posixfs-storage-driver/#setup-configuration
					"STORAGE_USERS_DRIVER": "posix",
					"STORAGE_USERS_POSIX_ROOT":"/home/jfd/tmp/posix-storage",
					"STORAGE_USERS_POSIX_WATCH_TYPE":"inotifywait",
					"STORAGE_USERS_ID_CACHE_STORE":"nats-js-kv", // why does it have to be nats?
					"STORAGE_USERS_ID_CACHE_STORE_NODES":"localhost:9233",
					
					// Optionally enable gid based space access
					//export STORAGE_USERS_POSIX_USE_SPACE_GROUPS="true"   

					
					/*
					 * Keep secrets and passwords in one block to allow easy uncommenting
					 */
					// user id of "admin", for user creation and admin role assignement
					"OCIS_ADMIN_USER_ID": "some-admin-user-id-0000-000000000000", // FIXME currently must have the length of a UUID, see reva/pkg/storage/utils/decomposedfs/spaces.go:228
					// admin user default password
					"IDM_ADMIN_PASSWORD": "admin",
					// system user
					"OCIS_SYSTEM_USER_ID": "some-system-user-id-000-000000000000", // FIXME currently must have the length of a UUID, see reva/pkg/storage/utils/decomposedfs/spaces.go:228
					"OCIS_SYSTEM_USER_API_KEY": "some-system-user-machine-auth-api-key",
					// set some hardcoded secrets
					"OCIS_JWT_SECRET": "some-ocis-jwt-secret",
					"OCIS_MACHINE_AUTH_API_KEY": "some-ocis-machine-auth-api-key",
					"OCIS_TRANSFER_SECRET": "some-ocis-transfer-secret",
					// idm ldap
					"IDM_SVC_PASSWORD": "some-ldap-idm-password",
					"GRAPH_LDAP_BIND_PASSWORD": "some-ldap-idm-password",
					// reva ldap
					"IDM_REVASVC_PASSWORD": "some-ldap-reva-password",
					"GROUPS_LDAP_BIND_PASSWORD": "some-ldap-reva-password",
					"USERS_LDAP_BIND_PASSWORD": "some-ldap-reva-password",
					"AUTH_BASIC_LDAP_BIND_PASSWORD": "some-ldap-reva-password",
					// idp ldap
					"IDM_IDPSVC_PASSWORD": "some-ldap-idp-password",
					"IDP_LDAP_BIND_PASSWORD": "some-ldap-idp-password",
					// storage users mount ID
					"GATEWAY_STORAGE_USERS_MOUNT_ID": "storage-users-1",
					"STORAGE_USERS_MOUNT_ID": "storage-users-1",
					// graph application ID
					"GRAPH_APPLICATION_ID": "application-1",

					// service accounts
					"OCIS_SERVICE_ACCOUNT_ID": "service-account-id",
					"OCIS_SERVICE_ACCOUNT_SECRET": "service-account-secret",

				}
			},
```

**Comment by butonic** [comment]
hm
```
2024-09-10T09:54:00+02:00 ERR error reading trash link error="readlink /home/jfd/tmp/posix-storage/spaces/e2/b2edae-0b58-420c-a340-1f979a358ba1/trash/fa/21/50/2d/-9bbf-45f3-bb17-916109f370c7: no such file or directory" key=fa21502d-9bbf-45f3-bb17-916109f370c7 pkg=rgrpc relative_path= service=storage-users spaceid=e2b2edae-0b58-420c-a340-1f979a358ba1 traceid=0b569fe44df68d41abf6500481c59bbb trashRoot=/home/jfd/tmp/posix-storage/spaces/e2/b2edae-0b58-420c-a340-1f979a358ba1/trash/fa/21/50/2d/-9bbf-45f3-bb17-916109f370c7
2024-09-10T09:54:00+02:00 ERR failed to list recycle error="readlink /home/jfd/tmp/posix-storage/spaces/e2/b2edae-0b58-420c-a340-1f979a358ba1/trash/fa/21/50/2d/-9bbf-45f3-bb17-916109f370c7: no such file or directory" key=fa21502d-9bbf-45f3-bb17-916109f370c7 pkg=rgrpc reference={"path":"./a1","resource_id":{"opaque_id":"e2b2edae-0b58-420c-a340-1f979a358ba1","space_id":"e2b2edae-0b58-420c-a340-1f979a358ba1","storage_id":"storage-users-1"}} service=storage-users status={"code":15,"message":"error listing recycle","trace":"0b569fe44df68d41abf6500481c59bbb"} traceid=0b569fe44df68d41abf6500481c59bbb
2024-09-10T09:54:00+02:00 ERR error gathering members for event error="error listing recycle: error listing recycle" event={"Event":{"Executant":{"idp":"https://cloud.ocis.test","opaque_id":"some-admin-user-id-0000-000000000000","type":1},"ID":{"opaque_id":"fa21502d-9bbf-45f3-bb17-916109f370c7","space_id":"e2b2edae-0b58-420c-a340-1f979a358ba1","storage_id":"storage-users-1"},"Owner":null,"Ref":{"path":"./a1","resource_id":{"opaque_id":"e2b2edae-0b58-420c-a340-1f979a358ba1","space_id":"e2b2edae-0b58-420c-a340-1f979a358ba1","storage_id":"storage-users-1"}},"SpaceOwner":{"idp":"https://cloud.ocis.test","opaque_id":"some-admin-user-id-0000-000000000000","type":1},"Timestamp":{"nanos":43455299,"seconds":1725954840}},"ID":"0cffd4b3-87cf-4998-8a0f-4e98dd82a47a","InitiatorID":"9361559d-7913-4337-b657-ec752d07b101","TraceParent":"00-176aaf3a64f9936fedff60caaf02edde-b86103ea760f187a-00","Type":"events.ItemTrashed"} service=clientlog
```

**Comment by aduffeck** [comment]
@butonic Could you take another look? It works as expected also with memory filemetadata cache for me now.

**Review by butonic — APPROVED** [review]
cool, yeah this works!

**Pull request merged**
