### PR TITLE
CS3 pulltransfer

### PR DESCRIPTION
**Pull request by redblom**
New CS3 datatx methods to support pull model. 
See https://github.com/cs3org/cs3apis/pull/134

### CODE REVIEW

**Comment by ishank011** [comment]
@redblom do we have the complete workflow now? Did you run any end-to-end tests?

**Comment by redblom** [comment]
@ishank011 : end-to-end create/accept share tests are successful (both regular and tx shares)

**Comment by ishank011** [comment]
I don't see the implementation? Can you create a single PR for the changes? And add the command usage and workflow to the description? (Something like https://github.com/cs3org/reva/pull/1743#issue-656417871)

**Comment by redblom** [comment]
@ishank011 : I'm struggling to get the dest webdav endpoint at service.datatx level that's needed for the rclone driver call. There's no access there to the gateway funcs.
Should I inject gateway access or ... inject the dest webdav endpoint?

Or maybe the CS3 PullTransferRequest is simply lacking the destination targetURI ... so maybe it should have targetURIs for both src and dest ?

**Comment by redblom** [comment]
@ishank011 : the home dir is part of the src file path, eg. `/home/mybigfiles/files-to-transfer ...`
Upon transfer the files will then be uploaded at dest to `/home/Data-Transfers/home/mybigfiles/files-to-transfer ...`

To me this seems a bit odd. I'm actually wondering if a home dir should be part of a share path at all ?

**Comment by ishank011** [comment]
Yep you just take the base path from the target and prepend the configurable data-transfers directory to get the full destination path.

**Comment by redblom** [comment]
Superseded by https://github.com/cs3org/reva/pull/2052

**Pull request closed without merging**
