### PR TITLE
[tests-only][full-ci]Bump latest ocis commit id

### PR DESCRIPTION
**Pull request by PrajwolAmatya**
Part of https://github.com/owncloud/QA/issues/867

### CODE REVIEW

**Comment by ScharfViktor** [comment]
I'm sorry. I pressed the wrong button.

**Comment by phil-davis** [comment]
@nirajacharya2 @PrajwolAmatya note that there is also PR #4938 - I guess that can be closed.

**Comment by saw-jan** [comment]
Upload steps are flaky in posixfs pipelines
```
Failed step: And user "Alice" has uploaded file with content "file to delete" to "/textfile0.txt"
        HTTP status code was not 201 or 204 while trying to upload file '/textfile0.txt' for user 'Alice'
        Failed asserting that an array contains 404.
```
CC @aduffeck

**Comment by saw-jan** [comment]
Waiting for PR https://github.com/owncloud/ocis/pull/10622

**Comment by saw-jan** [comment]
Ready to be merged

**Pull request merged**
