### PR TITLE
[tests-only][full-ci]Bump latest-ocis commit to reva master

### PR DESCRIPTION
**Pull request by SagarGi**
Part of: https://github.com/owncloud/QA/issues/805
This PR bumps the ocis commit id for tests

### CODE REVIEW

**Comment by SagarGi** [comment]
When bumping the latest commit, the pipeline gets killed. But when i use the older commits the pipeline get passed. May be a debug is required for which commit the pipeline gets killed.

**Comment by SagarGi** [comment]
checking in edge if it also has the same problem: https://github.com/cs3org/reva/pull/3803 with this PR

**Comment by SagarGi** [comment]
The bad commit changes that has stuck the pipeline is because of this PR changes in PR https://github.com/owncloud/ocis/commit/1a31aba659f7b148eecf0677bbb3491394331fef.

**Comment by phil-davis** [comment]
https://github.com/cs3org/reva/actions/runs/4804580793/jobs/8550227128?pr=3776
```
failed to remove network docker_default: Error response from daemon: error while removing network: network docker_default id ab95f490ea59f25884bbfcda14fc61c2bda8ba7bb1818dcbeb1cb14b824aa25b has active endpoints
make: *** [Makefile:130: docker-clean] Error 1
```

failure seems unrelated to the actual acceptance tests.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@labkode @glpatcern @gmgigi96 please review.
We needed to touch `.drone.star` so GitHub wants a code-owner review.

**Review by individual-it — APPROVED** [review]

**Review by glpatcern — APPROVED** [review]

**Pull request merged**
