### PR TITLE
[tests-only] Bump commit id for core API tests

### PR DESCRIPTION
**Pull request by phil-davis**
Includes a new scenario from core PR https://github.com/owncloud/core/pull/38395 in the testing.

### CODE REVIEW

**Comment by ishank011** [comment]
@phil-davis can you force push once? The CI didn't run but that has been fixed now.

**Comment by phil-davis** [comment]
Rebased - let's see what CI thinks now.

**Comment by labkode** [comment]
@phil-davis was triggered now

**Comment by phil-davis** [comment]
@labkode @ishank011 I rebased and sorted this out. Ready for review and merge.

**Review by labkode — APPROVED** [review]

**Pull request merged**
