### PR TITLE
[tests-only] [full-ci] Bump CORE_COMMITID to include new trashbin test code

### PR DESCRIPTION
**Pull request by phil-davis**
https://github.com/owncloud/QA/issues/738

Runs trashbin test changes that were just merged to core master in PR https://github.com/owncloud/core/pull/40050

Add code from #2821 to backport "fix trash-bin propfind responses" to master branch.

https://github.com/owncloud/QA/issues/739

### CODE REVIEW

**Comment by phil-davis** [comment]
I did a quick cherry-pick from #2821 but there are more things in the `edge` version of `formatTrashPropfind` so a "simple" backport does not work. It needs other prior code changes to also be backported so that the "edge" way of passing paramegters around and constructing the correct trashbin PROPFIND XML response can work.

@C0rby what to do? I would like to get the latest test code passing, rather than add a list of trashbin scenarios to expected-failures in master.

**Comment by phil-davis** [comment]
Note: without trying to fix the trashbin code, we get this list of fails:
https://drone.cernbox.cern.ch/cs3org/reva/6979/14/6
```
runsh: Total unexpected failed scenarios throughout the test run:
apiTrashbin/trashbinDelete.feature:29
apiTrashbin/trashbinDelete.feature:30
apiTrashbin/trashbinDelete.feature:53
apiTrashbin/trashbinDelete.feature:80
apiTrashbin/trashbinDelete.feature:103
apiTrashbin/trashbinDelete.feature:125
apiTrashbin/trashbinDelete.feature:147
apiTrashbin/trashbinDelete.feature:172
apiTrashbin/trashbinDelete.feature:197
apiTrashbin/trashbinDelete.feature:234
apiTrashbin/trashbinDelete.feature:271
apiTrashbin/trashbinDelete.feature:319
apiTrashbin/trashbinFilesFolders.feature:20
apiTrashbin/trashbinFilesFolders.feature:36
apiTrashbin/trashbinFilesFolders.feature:54
apiTrashbin/trashbinFilesFolders.feature:75
apiTrashbin/trashbinFilesFolders.feature:94
apiTrashbin/trashbinFilesFolders.feature:130
apiTrashbin/trashbinFilesFolders.feature:153
apiTrashbin/trashbinFilesFolders.feature:303
apiTrashbin/trashbinFilesFolders.feature:304
apiTrashbin/trashbinFilesFolders.feature:305
apiTrashbin/trashbinFilesFolders.feature:306
apiTrashbin/trashbinFilesFolders.feature:307
apiTrashbin/trashbinFilesFolders.feature:308
apiTrashbin/trashbinFilesFolders.feature:329
apiTrashbin/trashbinFilesFolders.feature:349
apiTrashbin/trashbinFilesFolders.feature:403
apiTrashbin/trashbinFilesFolders.feature:440
apiTrashbin/trashbinSharingToShares.feature:24
apiTrashbin/trashbinSharingToShares.feature:207
apiTrashbin/trashbinSharingToShares.feature:231
apiTrashbinRestore/trashbinRestore.feature:34
apiTrashbinRestore/trashbinRestore.feature:35
apiTrashbinRestore/trashbinRestore.feature:50
apiTrashbinRestore/trashbinRestore.feature:51
apiTrashbinRestore/trashbinRestore.feature:68
apiTrashbinRestore/trashbinRestore.feature:69
apiTrashbinRestore/trashbinRestore.feature:88
apiTrashbinRestore/trashbinRestore.feature:89
apiTrashbinRestore/trashbinRestore.feature:90
apiTrashbinRestore/trashbinRestore.feature:91
apiTrashbinRestore/trashbinRestore.feature:92
apiTrashbinRestore/trashbinRestore.feature:93
apiTrashbinRestore/trashbinRestore.feature:108
apiTrashbinRestore/trashbinRestore.feature:109
apiTrashbinRestore/trashbinRestore.feature:110
apiTrashbinRestore/trashbinRestore.feature:111
apiTrashbinRestore/trashbinRestore.feature:130
apiTrashbinRestore/trashbinRestore.feature:131
apiTrashbinRestore/trashbinRestore.feature:204
apiTrashbinRestore/trashbinRestore.feature:205
apiTrashbinRestore/trashbinRestore.feature:219
apiTrashbinRestore/trashbinRestore.feature:220
apiTrashbinRestore/trashbinRestore.feature:234
apiTrashbinRestore/trashbinRestore.feature:235
apiTrashbinRestore/trashbinRestore.feature:249
apiTrashbinRestore/trashbinRestore.feature:250
apiTrashbinRestore/trashbinRestore.feature:251
apiTrashbinRestore/trashbinRestore.feature:252
apiTrashbinRestore/trashbinRestore.feature:253
apiTrashbinRestore/trashbinRestore.feature:254
apiTrashbinRestore/trashbinRestore.feature:271
apiTrashbinRestore/trashbinRestore.feature:272
apiTrashbinRestore/trashbinRestore.feature:289
apiTrashbinRestore/trashbinRestore.feature:290
apiTrashbinRestore/trashbinRestore.feature:309
apiTrashbinRestore/trashbinRestore.feature:310
apiTrashbinRestore/trashbinRestore.feature:329
apiTrashbinRestore/trashbinRestore.feature:330
apiTrashbinRestore/trashbinRestore.feature:363
apiTrashbinRestore/trashbinRestore.feature:364
apiTrashbinRestore/trashbinRestore.feature:402
apiTrashbinRestore/trashbinRestore.feature:403
apiTrashbinRestore/trashbinRestore.feature:441
apiTrashbinRestore/trashbinRestore.feature:442
apiTrashbinRestore/trashbinRestore.feature:459
apiTrashbinRestore/trashbinRestore.feature:460
apiTrashbinRestore/trashbinRestore.feature:478
apiTrashbinRestore/trashbinRestore.feature:479
apiTrashbinRestore/trashbinRestore.feature:502
apiTrashbinRestore/trashbinRestore.feature:503
apiTrashbinRestore/trashbinRestore.feature:521
apiTrashbinRestore/trashbinRestore.feature:522
apiTrashbinRestore/trashbinRestore.feature:536
apiTrashbinRestore/trashbinRestore.feature:537
apiTrashbinRestore/trashbinRestore.feature:589
apiTrashbinRestore/trashbinRestore.feature:590
apiWebdavEtagPropagation2/restoreFromTrash.feature:26
apiWebdavEtagPropagation2/restoreFromTrash.feature:27
apiWebdavEtagPropagation2/restoreFromTrash.feature:49
apiWebdavEtagPropagation2/restoreFromTrash.feature:50
apiWebdavEtagPropagation2/restoreFromTrash.feature:70
apiWebdavEtagPropagation2/restoreFromTrash.feature:71
apiWebdavEtagPropagation2/restoreFromTrash.feature:93
apiWebdavEtagPropagation2/restoreFromTrash.feature:94
runsh: There were no unexpected success.
```

That is a lot of scenarios that fail because the test code now expects really-correct trashbin PROPFIND XML responses.

**Comment by phil-davis** [comment]
Note: bumping the core commit id in master branch (this PR) is blocked until we decide what to do:

1) accept that master branch does not have perfect trashbin PROPFIND responses - add the long lits of test fails to expected failures, or:
2) fix the code in master branch (which is not a straightforward backport)

**Comment by phil-davis** [comment]
To get this unblocked, I have done option (1)
"accept that master branch does not have perfect trashbin PROPFIND responses - add the long lits of test fails to expected failures"

I raised issue #2861 and listed the relevant scenarios under that issue in expected-failures.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
