### PR TITLE
Site accounts update

### PR DESCRIPTION
**Pull request by Daniel-WWU-IT**
Yet another PR to update the site accounts (and Mentix):

- New default site ID
- Include service type in alerts
- Naming unified
- Remove obsolete stuff

### CODE REVIEW

**Comment by labkode** [comment]
@Daniel-WWU-IT can you rebase the changes?

**Comment by Daniel-WWU-IT** [comment]
@labkode Rebased and (still) green. Can this be merged now?

**Review by glpatcern — APPROVED** [review]

**Review by glpatcern — CHANGES_REQUESTED** [review]
Hi Daniel, are you sure the rebase worked correctly? It seems the PR brings many more changes than it was supposed to

**Comment by Daniel-WWU-IT** [comment]
> Hi Daniel, are you sure the rebase worked correctly? It seems the PR brings many more changes than it was supposed to

Rebase _never_ works for me, and I frankly don't know how to get rid of those superfluous commits...

**Comment by Daniel-WWU-IT** [comment]
Replaced by https://github.com/cs3org/reva/pull/2672

**Pull request closed without merging**
