### PR TITLE
Public Links

### PR DESCRIPTION
**Pull request by refs**
# What?

DAV Api for public shares. Currently displaying public shares depends on https://github.com/owncloud/phoenix/pull/2494. 

Is there a way to access a resource in behalf of the resource owner that is not through basic auth?

- [x] show user shares and public shares on the sidebar
- [x] reachable publicShare handler
- [x] whitelist public share urls (in order to access a public share)

### CODE REVIEW

**Comment by labkode** [comment]
@refs we need to rebase this on master

**Comment by refs** [comment]
@labkode Indeed we need to rebase master onto this branch. I tried to update it every once in a while, will do ASAP.

Next week I'm spending time on Reva, so will resume this from next week on! Been busy with the extensions.

**Comment by labkode** [comment]
@refs glad to hear that :)

**Comment by refs** [comment]
@labkode branch updated, resuming work on this now :)

**Comment by labkode** [comment]
@refs is this still WIP or ready to merge?

**Comment by refs** [comment]
> @refs is this still WIP or ready to merge?

Still WIP. Getting up to speed on Reva :)

**Comment by butonic** [comment]
:rocket: works!

**Comment by refs** [comment]
cc @labkode we still need to figure out a few bits and , but creating public links works.

**Pull request merged**
