### PR TITLE
Forward OpenFileInAppProvider calls for OCM shares to remote reva

### LINKED ISSUE #1032: Riva overwrite content directory
If I'm upload file to root path "/" Reva overwrite user content directory with single file. User lost all data.

Steps to reproduce:

```
cd reva/cmd/reva
echo "Test" >test.txt
./reva --insecure login basic
./reva --insecure upload test.txt /
```
after this operation directory "/var/tmp/reva/data" has only file "einstein", not directory "einstein"

### PR DESCRIPTION
**Pull request by ishank011**
Also closes #1032

### CODE REVIEW

**Review by glpatcern — DISMISSED** [review]
Looks good, and I guess the gateway's `Stat` will take care of all that is needed (including forwarding remote errors that will be embedded in the `OpenFileInAppProviderResponse`).

**Comment by ishank011** [comment]
@glpatcern nope, we append `info` to the list of shares. We'll update info only if there's no error returned from the webdav stat call, otherwise we'll just let it continue to have the stat response of the reference, which it previously did.

**Review by glpatcern — COMMENTED** [review]
Now this one looks good

**Review by SamuAlfageme — CHANGES_REQUESTED** [review]
While testing this, we've seen that the 'username' encoded on the JWT token that gets forwarded to the WOPI Server (via Collabora) is the same for both the issuer and the receiver of the share:

```json
{
   "typ":"JWT",
   "alg":"HS256"
}{
   "userid":"...",
   "filename":"/reva/daniel/test4/test.odt",
   "username":"daniel",
   "viewmode":"VIEW_MODE_READ_WRITE",
   "folderurl":"undefined",
   "exp":1599906112,
 }
```

Therefore, it renders the same username for both parties during a collaborative editing session. cc/ @glpatcern

**Comment by ishank011** [comment]
Can't do that with the current implementation. We're passing the same token around as the original user and can't make changes to it as we don't know the jwt secret of the other site. This won't be an issue in the public shares implementation so I think we can leave it be.

**Review by labkode — APPROVED** [review]

**Pull request merged**
