### PR TITLE
Efss backend fixes

### PR DESCRIPTION
**Pull request by labkode**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Integration tests are failing with `decomposedfs: could not set parentid attribute`

**Comment by gmgigi96** [comment]
@michielbdejong Did you get the error on your local machine?

**Comment by michielbdejong** [comment]
No, on https://cs3org-reva-1tfel8t6msj.ws-eu77.gitpod.io/ I made the workspace public so you should probably be able to see it there (choose 'VSCode Browser' as the editor)

**Comment by michielbdejong** [comment]
```
sudo apt install -y redis
export REDIS_ADDRESS=127.0.0.1:6379
make test-integration
```

I see /tmp/reva-grpc-integration-tests-2961286421-root gets created, not sure why it says it can't set the parent id. Should /tmp be any particular filesystem?

**Comment by labkode** [comment]
> ```
> sudo apt install -y redis
> export REDIS_ADDRESS=127.0.0.1:6379
> make test-integration
> ```
> 
> I see /tmp/reva-grpc-integration-tests-2961286421-root gets created, not sure why it says it can't set the parent id. Should /tmp be any particular filesystem?

It should support settings extended attributed (xattrs), usually /tmp is memfs-alike

**Comment by michielbdejong** [comment]
```
• Failure in Spec Setup (JustBeforeEach) [1.050 seconds]
storage providers
/workspace/reva/tests/integration/grpc/storageprovider_test.go:47
  nextcloud
  /workspace/reva/tests/integration/grpc/storageprovider_test.go:466
    with an existing file /versioned_file
    /workspace/reva/tests/integration/grpc/storageprovider_test.go:499
      restores a file version [JustBeforeEach]
      /workspace/reva/tests/integration/grpc/storageprovider_test.go:163

      Unexpected error:
          <*errors.withStack | 0xc000012258>: {
              error: <*errors.withMessage | 0xc0005aac60>{
                  cause: <*errors.withStack | 0xc000012228>{
                      error: <*errors.withMessage | 0xc0005aac20>{
                          cause: <*xattr.Error | 0xc00074cc40>{
                              Op: "xattr.Set",
                              Path: "/tmp/reva-grpc-integration-tests-667258874-root/nodes/root",
                              Name: "user.ocis.parentid",
                              Err: <syscall.Errno>0x5f,
                          },
                          msg: "decomposedfs: could not set parentid attribute",
                      },
                      stack: [0xe71acb, 0xe85077, 0xe7ed25, 0xebff0f, 0xebfb87, 0xedc9ba, 0xeec6b9, 0x967778, 0x966e78, 0x967c15, 0x96b6c9, 0x96ad58, 0x99f725, 0x99f311, 0x99e565, 0x9a1a45, 0x9b6af3, 0x9b6870, 0xee86ae, 0x5b68b7, 0x4a5ec1],
                  },
                  msg: "could not setup tree",
              },
              stack: [0xebff85, 0xebfb87, 0xedc9ba, 0xeec6b9, 0x967778, 0x966e78, 0x967c15, 0x96b6c9, 0x96ad58, 0x99f725, 0x99f311, 0x99e565, 0x9a1a45, 0x9b6af3, 0x9b6870, 0xee86ae, 0x5b68b7, 0x4a5ec1],
          }
          could not setup tree: decomposedfs: could not set parentid attribute: xattr.Set /tmp/reva-grpc-integration-tests-667258874-root/nodes/root user.ocis.parentid: operation not supported
      occurred

      /workspace/reva/tests/integration/grpc/storageprovider_test.go:505
------------------------------
```

**Comment by vascoguita** [comment]
To pass the linter just run `make lint-fix` before pushing

**Comment by vascoguita** [comment]
One last remark,
The CI jobs are being triggered twice because we have both a push to an upstream branch and a PR.
It would be better to make PRs from Forks instead of using upstream directly.
@michielbdejong Do you have a fork of Reva from which you could make this PR instead of cs3org/reva:efss-backend-fixes?

**Pull request closed without merging**
