### PR TITLE
[tests-only] remove the owncloud storage driver tests from CI

### PR DESCRIPTION
**Pull request by C0rby**
We don't need the owncloud storage driver anymore so it doesn't make sense to spend time and CPU cycles running these tests.

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
There should also be an expected-failures file that can be deleted.

**Comment by C0rby** [comment]
True! I forgot about it. :+1:

**Review by micbar — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Review by labkode — APPROVED** [review]

**Comment by labkode** [comment]
@phil-davis @C0rby should the README https://github.com/cs3org/reva/blob/master/README.md be updated as well?

**Comment by phil-davis** [comment]
> @phil-davis @C0rby should the README https://github.com/cs3org/reva/blob/master/README.md be updated as well?

PR #1951 - I didn't find much that references the `owncloud` storage driver.

**Pull request merged**
