### PR TITLE
use gateway to resolve public share info

### PR DESCRIPTION
**Pull request by butonic**
alternative approach to https://github.com/cs3org/reva/pull/822

### CODE REVIEW

**Comment by PVince81** [comment]
To retest:
- [ ] upload with folder share
- [ ] download with folder share
- [ ] download with single file share

**Comment by PVince81** [comment]
- [ ] TODO: cleanup potential dead code / stuff that is not needed any more
- [ ] close ocis-reva and ocis PRs as they are not needed any more (we don't need a public link data provider)
- [ ] check review comments from https://github.com/cs3org/reva/pull/822

@refs FYI

**Comment by PVince81** [comment]
- [ ] set Expose: false, but need investigation on https://github.com/owncloud/ocis-proxy/pull/45 as it didn't work when we tested

**Comment by PVince81** [comment]
PR here to fix upload and implement some more operations: https://github.com/butonic/reva/pull/5

still need to look at single file share which is currently broken here

**Comment by PVince81** [comment]
cool, so all tests I've enabled pass except the ones for single file share, which is the last thing that needs fixing:
```
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature:643
    /srv/www/htdocs/owncloud/tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature:644
```

**Comment by PVince81** [comment]
Further work here for the linter and code reuse: https://github.com/butonic/reva/pull/6

**Comment by PVince81** [comment]
Regarding single file share:

@butonic and I had a long session and found out that:
- we agreed that it is not a good idea to add the virtual folder on the CS3 layer, so we need to do it on the Webdav layer. The current approach is a mix of both.
- to do public file share in proper way we need to separate the logic for the virtual folder. We started something here: https://github.com/butonic/reva/pull/7

Since I'd like to have something merged, we'll split the topics, so here are the next steps:

- [ ] finalize public upload/download for **folders shares**:
   - [ ] clean up this PR (#872) and remove all extra coded that was added for single file share as it's broken and likely obsolete with the new solution
   - [ ] commit the existing API tests
   - [ ] get it merged and released
- [ ] in parallel: work on a separate branch to further explore the solution for single file shares: https://github.com/butonic/reva/pull/7

**Comment by PVince81** [comment]
@butonic I've submitted the features that already work in a separate PR https://github.com/cs3org/reva/pull/877 so that we can merge those first.

we can keep your branch here "refactor-public-links-download" to continue exploring the single file share implementation.

**Comment by PVince81** [comment]
please rebase. or should we start a brand new pr for file shares?

**Comment by butonic** [comment]
obsoleted by https://github.com/cs3org/reva/pull/877

**Pull request closed without merging**
