### PR TITLE
build: fix Makefile to use go env GOPATH

### PR DESCRIPTION
**Pull request by labkode**
Needed to export the GOPATH/bin for building on Mac.

Take the opportunity to also clean deps

### CODE REVIEW

**Comment by tboerger** [comment]
Using go run is much more accurate, than anybody is also using the same defined version of the tools as they are managed by the go modules config.

**Comment by labkode** [comment]
@tboerger I tried with go run but to version I need to version the dep inside the go.mod in Reva, running go run github.com/..@v1.0.0 outside the the reva repo didn't work for me.

If you can give it a try I prefer to just run go run that this workaround!

**Comment by tboerger** [comment]
What do you have against versioning it via go.mod? That ensures that this tool is really the same version for everybody. Imho that's a benefit as I gathered the knowledge that it could lead to different behavior otherwise.

**Comment by labkode** [comment]
@tboerger the license of `golangci-lint` is GPL and such license cannot be part of any Reva dependencies to guarantee its permissive adoption, that's the reason why I can't put it into the dependencies of the project.

**Comment by tboerger** [comment]
You could also replace golangci-lint by https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck which is MIT licensed :)

**Comment by labkode** [comment]
golangci-lint has more checks than staticcheck, indeed staticcheck is one of the test we run:

```
linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - golint
    - goimports
    - unconvert
    - scopelint
    - maligned
    - misspell
    - gocritic

```

**Pull request merged**
