### PR TITLE
Invite manager "api" for use with NC/OC-10

### PR DESCRIPTION
**Pull request by michielbdejong**
With this invite manager, OCM invites (both pending and accepted) will be stored in your EFSS instead of inside the revad server in a `/var/tmp/reva/ocm-invites.json` file which is the current standard behaviour for NC/OC-10 based ScienceMesh sites.

### CODE REVIEW

**Comment by gmgigi96** [comment]
Maybe "api" as name is too generic? I would call it "nextcloud" or "owncloud", like in the ocm share provider

**Comment by michielbdejong** [comment]
@mrvahedi68 can you resolve the Hound smells and answer the reviewer comment above?

Also, I'm seeing this in the mesh.pondersource.org logs:
2023-06-13 10:41:21.076 ERR ../reva/cmd/revad/runtime/runtime.go:219 > error starting the grpc server error="unable to register services: rgrpc: grpc service ocminvitemanager could not be started,: failed to build resolver: passthrough: received empty target in Build()" pid=292622
do you know what might cause that?
This is my config:
[grpc.services.ocminvitemanager]
driver = "api"
provider_domain = "mesh.pondersource.org"

[grpc.services.ocminvitemanager.drivers.api]
base_url = "https://cloud.pondersource.org/"
api_key = "shared-secret-1"

**Comment by mrvahedi68** [comment]
> @mrvahedi68 can you resolve the Hound smells and answer the reviewer comment above?
> 
> Also, I'm seeing this in the mesh.pondersource.org logs:
> 
> ```
> 2023-06-13 10:41:21.076 ERR ../reva/cmd/revad/runtime/runtime.go:219 > error starting the grpc server error="unable to register services: rgrpc: grpc service ocminvitemanager could not be started,: failed to build resolver: passthrough: received empty target in Build()" pid=292622
> ```
> 
> do you know what might cause that? This is my config:
> 
> ```
> [grpc.services.ocminvitemanager]
> driver = "api"
> provider_domain = "mesh.pondersource.org"
> 
> [grpc.services.ocminvitemanager.drivers.api]
> base_url = "https://cloud.pondersource.org/"
> api_key = "shared-secret-1"
> ```

It is for missing `gatewaysvc` configuration inside `api` configuration section.
Like this:
`
  [grpc.services.ocminvitemanager.drivers.api]
  base_url = "https://cloud.pondersource.org/"
  api_key = "shared-secret-1"
  gatewaysvc = "Put Here"
`

**Comment by glpatcern** [comment]
Superseded by #4115

**Pull request closed without merging**
