### PR TITLE
Reuse HTTP Clients

### PR DESCRIPTION
**Pull request by refs**
File descriptors on the ocdav service, especially on the put handler was leaking http connections. This PR addresses this.

### CODE REVIEW

**Comment by ishank011** [comment]
Thanks a lot for this @refs! I was looking at the storage provider tus methods and was pulling my hair. This should be good!

Can you fix the lint? We can merge it then

**Comment by refs** [comment]
> Thanks a lot for this @refs! I was looking at the storage provider tus methods for the leaks and was pulling my hair. This should be good!
> 
> Can you fix the lint? We can merge it then

haha, goland, too lazy to configure watchers :D on it

**Comment by refs** [comment]
@ishank011 imports should be good now. waiting for checks

**Comment by butonic** [comment]
datagateway is also leaking ... @refs is adding it to this pr

**Comment by butonic** [comment]
@ishank011 we should double check all places where the rhttp.GetHttpClient() is called. The context that is passed is not used anyway. So we can initialize the client when starting the services. That will allow reusing connections :rocket:

**Review by butonic — APPROVED** [review]

**Review by ishank011 — APPROVED** [review]
@butonic definitely. I'll get to fixing these next. Thanks!

**Pull request merged**
