### PR TITLE
Indicate in EOS containers that TUS is not supported

### PR DESCRIPTION
**Pull request by ishank011**

### CODE REVIEW

**Comment by ishank011** [comment]
@phil-davis can you take a look what's happening here? https://drone.cernbox.cern.ch/cs3org/reva/265/

**Comment by ishank011** [comment]
Never mind. My bad

**Review by butonic — APPROVED** [review]
ok it, it defaults to TUS being used and it has to be explicitly disabled. I don't know about all the implications for clients that still rely on the capabilities endpoint. but this is what will make ocis-web use normal PUT

**Comment by ishank011** [comment]
Thanks a lot @butonic! For the capabilities endpoint, I already added the code to control the response using config envs in https://github.com/cs3org/reva/pull/1331

**Pull request merged**
