### PR TITLE
Fix OS storage move propagation

### PR DESCRIPTION
**Pull request by PVince81**
Propagating on the source path failed because the source path does not exist any more after moving. This fix makes it start the propagation on the parent of the source.

I've also fixed the error handling because while debugging this it caused memory pointer errors as the errors were not propagated to the outside.

@butonic

### CODE REVIEW

**Comment by PVince81** [comment]
=> this makes the litmus webdav move tests pass!

**Comment by labkode** [comment]
@PVince81 just lint and is good to merge

**Comment by PVince81** [comment]
I've removed the stray debug code and fixed the linter errors by properly returning the error objects.

**Comment by PVince81** [comment]
all green, please merge :-)

**Pull request merged**
