### PR TITLE
[tests-only][full-ci]Bump core commit id for tests

### PR DESCRIPTION
**Pull request by SagarGi**
Part of: https://github.com/owncloud/QA/issues/736

This PR also include the following changes to remove jarnaiz/behat-junit-formatter as
Part of:  https://github.com/owncloud/QA/issues/737

### CODE REVIEW

**Comment by phil-davis** [comment]
@SagarGi please also remove `jarnaiz/behat-junit-formatter` for issue https://github.com/owncloud/QA/issues/737
It is just deleting references the same as in, for example, https://github.com/owncloud/search_elastic/pull/279

Also do the same for edge branch.

**Comment by SagarGi** [comment]
> @SagarGi please also remove `jarnaiz/behat-junit-formatter` for issue [owncloud/QA#737](https://github.com/owncloud/QA/issues/737) It is just deleting references the same as in, for example, [owncloud/search_elastic#279](https://github.com/owncloud/search_elastic/pull/279)
> 
> Also do the same for edge branch.

@phil-davis sure.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@labkode @ishank011 @glpatcern the changes here are all test-related, but enough that GitHub does not let me merge. Please review/approve/merge. Thanks.

**Review by individual-it — DISMISSED** [review]

**Comment by phil-davis** [comment]
@labkode @ishank011 @glpatcern PR has been updated for the latest core test changes. GitHub does not let me merge. Please review/approve/merge. Thanks.

**Review by glpatcern — APPROVED** [review]

**Comment by phil-davis** [comment]
@labkode or @ishank011 - this has been updated again and is passing against the latest core acceptance tests.
Please review and merge.

**Comment by phil-davis** [comment]
@labkode or @ishank011 we are stuck - can you please take 1 minute to press approve and merge?

**Review by ishank011 — APPROVED** [review]

**Pull request merged**
