### PR TITLE
Data transfers package

### PR DESCRIPTION
**Pull request by ishank011**
Previously, we had to configure which data transfer protocol to use in the dataprovider service. A previous PR added the functionality to redirect requests to different handlers based on the request method but that would lead to conflicts if multiple protocols don't support mutually exclusive sets of requests. This PR adds the functionality to have multiple such handlers simultaneously and the client can choose which protocol to use.

Depends on https://github.com/cs3org/cs3apis/pull/96, currently uses my fork https://github.com/ishank011/go-cs3apis

`InitiateFileUpload` response now looks like:
```
{
  "status": {
    "code": 1
  },
  "protocols": [
    {
      "protocol": "simple",
      "upload_endpoint": "http://localhost:19001/datagateway",
      "available_checksums": [
        {
          "type": 3,
          "priority": 100
        },
        {
          "type": 1,
          "priority": 1000
        }
      ],
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjA1NjM2MzQ0LCJpYXQiOjE2MDU2MzAzNDQsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTcwMDEvZGF0YS9zaW1wbGUvYjk1YjhlOGUtYTgwYi00NjMxLWI3OTgtNTJjY2ZjOGExMTM1In0.g68M_LkQ9Loaz9sJedMK_DmrNMhKwe2R0NNC7gtwYvw"
    },
    {
      "protocol": "tus",
      "upload_endpoint": "http://localhost:19001/datagateway",
      "available_checksums": [
        {
          "type": 3,
          "priority": 100
        },
        {
          "type": 1,
          "priority": 1000
        }
      ],
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjA1NjM2MzQ0LCJpYXQiOjE2MDU2MzAzNDQsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTcwMDEvZGF0YS90dXMvYjk1YjhlOGUtYTgwYi00NjMxLWI3OTgtNTJjY2ZjOGExMTM1In0.AhV2jABWns8t8-YiEQkzAleuTnL5kpVEYxbpOebtCYM"
    }
  ]
}
```

### CODE REVIEW

**Comment by labkode** [comment]
@ishank011 I merged the cs3apis, let's change the dep to it

**Review by labkode — CHANGES_REQUESTED** [review]
@ishank011 should we remove the sdk test files?

**Comment by ishank011** [comment]
@labkode Yes we can. I didn't like the idea of calling a remote server to run unit tests in the first place.

@Daniel-WWU-IT can you modify these to run on a local reva daemon?

**Comment by labkode** [comment]
@ishank011 still one conflict to resolve

**Review by labkode — APPROVED** [review]

**Pull request merged**
