### PR TITLE
Nextcloud share manager

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
I restarted the continuous integration due to intermittent integration test failures (see https://gitter.im/cs3org/REVA?at=614ad59711793469662e7d70)

**Comment by michielbdejong** [comment]
Now it's green.
Can someone please review?

**Comment by ishank011** [comment]
@michielbdejong can you rebase?

**Comment by michielbdejong** [comment]
Yes! Rebased.

**Review by ishank011 — APPROVED** [review]

**Pull request merged**
