### PR TITLE
Dummy implementation of the Lock CS3APIs

### PR DESCRIPTION
**Pull request by wkloucek**
needs https://github.com/cs3org/cs3apis/pull/160

### CODE REVIEW

**Review by glpatcern — APPROVED** [review]

**Comment by C0rby** [comment]
@wkloucek, the CS3API PR was merged. You can update this PR. :)

**Comment by wkloucek** [comment]
> @wkloucek, the CS3API PR was merged. You can update this PR. :)

needs https://github.com/cs3org/reva/pull/2369 first from my pov

**Comment by labkode** [comment]
@wkloucek done

**Comment by C0rby** [comment]
@wkloucek, cool now we can rebase this one. :)

**Review by C0rby — APPROVED** [review]

**Review by labkode — APPROVED** [review]

**Pull request merged**
