### PR TITLE
[meshdirectory] New UI frontend with project branding

### PR DESCRIPTION
**Pull request by mirekys**
Replaces the temporary version of web frontend of the mesh directory http service with
a new redesigned & branded one.

Because the new frontend is a more complex Vue SPA that contains image,
css and other assets, it is now served from a binary package distribution that was generated using the
[github.com/rakyll/statik](https://github.com/rakyll/statik) package. The `http.services.meshdirectory.static`
config option will be obsoleted by this change.

@labkode what should be the best place to put the Vue frontend sources into?
Is it ok to create e.g. `meshdirectory-web` repo under @sciencemesh or @cs3org for it?

Screenshot_2021-02-26 Mesh Directory ScienceMesh

Fixes https://github.com/cs3org/reva/issues/1502

### CODE REVIEW

**Comment by SamuAlfageme** [comment]
@mirekys omg, this is awesome - might I suggest some icons on the footer "Resources" links? Awesome work! 👏

**Comment by labkode** [comment]
@mirekys this is really good! We can host it under sciencemesh org. I give you admin perms so you can create the repo.
For the static site generation to embeed the binary, 1.16 has just got support to embeed his natively in case you want to give it a try.

**Comment by pferreir** [comment]
Great work, @mirekys. If you just allow me to nitpick on something, that "account." at the bottom looks a bit out of place to me. I would rather reword the text on top to say "using your account at" and leave the bottom part empty.

**Comment by mirekys** [comment]
Thanks to all for the tips! Please have a look at [meshdirectory-web](https://github.com/sciencemesh/meshdirectory-web) if I managed to address them all. I also went for embedding the app using the new 'embed'. It works nicely and is a cleaner approach, if there isn't any problem with raising the minimal required Go version on reva to 1.16 (CI fails currently).

**Comment by labkode** [comment]
@mirekys sorry for late reply. Can you bump the go version in this PR for the CI as well? We should make it green.

**Comment by mirekys** [comment]
@labkode bumped go & fixed build, but not sure what causes LGTM to complain about:
```
[2021-03-12 15:37:42] [build-err] Only found JavaScript or TypeScript files that were empty or contained syntax errors.
[2021-03-12 15:37:42] [ERROR] Spawned process exited abnormally (code 255; tried to run: [/opt/dist/javascript/tools/autobuild.sh])
```
there are no .js|.ts files touched in this PR

**Pull request merged**
