### PR TITLE
Add troubleshooting information

### PR DESCRIPTION
**Pull request by LovisaLugnegard**
Added some error logging and trouble shooting information, hopefully this won't be needed but if someone encounters this problem I hope this info saves some time.

### CODE REVIEW

**Comment by ishank011** [comment]
Instead of logging here, can you modify normalize to return both `*provider.ResourceInfo` and an error, and if the error is not nil, return the error from where it is called? I try to prevent adding any logging in the packages and instead pass them to the GRPC service.

**Comment by LovisaLugnegard** [comment]
Sure!

**Comment by ishank011** [comment]
They already do. normalize is an internal method which doesn't. All the heavy operations are carried out here and logging with a context is quite expensive as well.

**Comment by ishank011** [comment]
Also, the documentation doesn't belong in readme. You can add it to one of the tutorials.

**Comment by labkode** [comment]
@LovisaLugnegard more specifically, this should be documentation for the driver causing this problem.

**Comment by ishank011** [comment]
Okay yes, maybe we can add it under https://reva.link/docs/concepts/storages/#local-storage-driver?

**Comment by LovisaLugnegard** [comment]
How about adding a "troubleshooting" folder under documentation? 

@labkode "this should be documentation for the driver causing this problem." - I'm not sure I understand what you mean with this?

**Comment by butonic** [comment]
@LovisaLugnegard can you rebase please?

**Pull request closed without merging**
