### PR TITLE
Consistency Across XML and JSON Formats

### LINKED ISSUE #263: ocdav: correctly marshal to XML and JSON
From @refs:

LGTM. Needs to be followed up with a proper fix for this, that is the OCS api JSON and XML encoding diferr.

https://cloud.owncloud.com/ocs/v1.php/cloud/capabilities?format=json

...
"user": {
"send_mail": true
},
"resharing": true,
"group_sharing": true,
"auto_accept_share": true,
"share_with_group_members_only": true,
"share_with_membership_groups_only": true,
"can_share": true,
...
https://cloud.owncloud.com/ocs/v1.php/cloud/capabilities?format=xml

...
<user>
<send_mail>1</send_mail>
</user>
<resharing>1</resharing>
<group_sharing>1</group_sharing>
<auto_accept_share>1</auto_accept_share>
<share_with_group_members_only>1</share_with_group_members_only>
<share_with_membership_groups_only>1</share_with_membership_groups_only>
<can_share>1</can_share>
...

### PR DESCRIPTION
**Pull request by refs**
# What?

[ownCloud's capabilities endpoint](https://doc.owncloud.com/server/developer_manual/core/apis/ocs-capabilities.html) shows inconsistency between JSON and XML formats, see #263 for detailed formatting.

This PR adds a custom `ocsBoolean` that implements the Marshaler interface for XML and JSON. The 2 following outputs show its behavior:

XML:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<ocs>
    <meta>
        <status>ok</status>
        <statuscode>100</statuscode>
        <message>OK</message>
    </meta>
    <data>
        <capabilities>
            <core>
                <pollinterval>60</pollinterval>
                <webdav-root>remote.php/webdav</webdav-root>
                <status>
                    <installed>1</installed>
                    <maintenance>0</maintenance>
                    <needsDbUpgrade>0</needsDbUpgrade>
                    <version>10.0.9.5</version>
                    <versionstring>10.0.9</versionstring>
                    <edition>community</edition>
                    <productname>reva</productname>
                </status>
            </core>
            <checksums>
                <supportedTypes>
                    <element>SHA256</element>
                </supportedTypes>
                <preferredUploadType>SHA256</preferredUploadType>
            </checksums>
            <files>
                <privateLinks>1</privateLinks>
                <bigfilechunking>1</bigfilechunking>
                <undelete>1</undelete>
                <versioning>1</versioning>
                <blacklisted_files>
                    <element>foo</element>
                </blacklisted_files>
            </files>
            <dav>
                <chunking>1.0</chunking>
                <trashbin>1.0</trashbin>
                <reports>
                    <element>search-files</element>
                </reports>
            </dav>
            <files_sharing>
                <api_enabled>1</api_enabled>
                <resharing>1</resharing>
                <group_sharing>1</group_sharing>
                <auto_accept_share>1</auto_accept_share>
                <share_with_group_members_only>1</share_with_group_members_only>
                <share_with_membership_groups_only>1</share_with_membership_groups_only>
                <search_min_length>3</search_min_length>
                <default_permissions>22</default_permissions>
                <user_enumeration>
                    <enabled>1</enabled>
                    <group_members_only>1</group_members_only>
                </user_enumeration>
                <federation>
                    <outgoing>1</outgoing>
                    <incoming>1</incoming>
                </federation>
                <public>
                    <enabled>1</enabled>
                    <send_mail>1</send_mail>
                    <social_share>1</social_share>
                    <upload>1</upload>
                    <multiple>1</multiple>
                    <supports_upload_only>1</supports_upload_only>
                    <password>
                        <enforced_for>
                            <read_only>1</read_only>
                            <read_write>1</read_write>
                            <upload_only>1</upload_only>
                        </enforced_for>
                        <enforced>1</enforced>
                    </password>
                    <expire_date>
                        <enabled>1</enabled>
                    </expire_date>
                </public>
                <user>
                    <send_mail>1</send_mail>
                </user>
            </files_sharing>
            <notifications>
                <ocs-endpoints>
                    <element>list</element>
                    <element>get</element>
                    <element>delete</element>
                </ocs-endpoints>
            </notifications>
        </capabilities>
        <version>
            <major>10</major>
            <minor>0</minor>
            <micro>11</micro>
            <string>10.0.11</string>
            <edition>nexus</edition>
        </version>
    </data>
</ocs>
```

JSON:
```json
{
    "ocs": {
        "meta": {
            "status": "ok",
            "statuscode": 100,
            "message": "OK"
        },
        "data": {
            "capabilities": {
                "core": {
                    "pollinterval": 60,
                    "webdav-root": "remote.php/webdav",
                    "status": {
                        "installed": true,
                        "maintenance": false,
                        "needsDbUpgrade": false,
                        "version": "10.0.9.5",
                        "versionstring": "10.0.9",
                        "edition": "community",
                        "productname": "reva"
                    }
                },
                "checksums": {
                    "supportedTypes": ["SHA256"],
                    "preferredUploadType": "SHA256"
                },
                "files": {
                    "privateLinks": true,
                    "bigfilechunking": true,
                    "undelete": true,
                    "versioning": true,
                    "blacklisted_files": ["foo"]
                },
                "dav": {
                    "chunking": "1.0",
                    "trashbin": "1.0",
                    "reports": ["search-files"]
                },
                "files_sharing": {
                    "api_enabled": true,
                    "resharing": true,
                    "group_sharing": true,
                    "auto_accept_share": true,
                    "share_with_group_members_only": true,
                    "share_with_membership_groups_only": true,
                    "search_min_length": 3,
                    "default_permissions": 22,
                    "user_enumeration": {
                        "enabled": true,
                        "group_members_only": true
                    },
                    "federation": {
                        "outgoing": true,
                        "incoming": true
                    },
                    "public": {
                        "enabled": true,
                        "send_mail": true,
                        "social_share": true,
                        "upload": true,
                        "multiple": true,
                        "supports_upload_only": true,
                        "password": {
                            "enforced_for": {
                                "read_only": true,
                                "read_write": true,
                                "upload_only": true
                            },
                            "enforced": true
                        },
                        "expire_date": {
                            "enabled": true
                        }
                    },
                    "user": {
                        "send_mail": true
                    }
                },
                "notifications": {
                    "ocs-endpoints": ["list", "get", "delete"]
                }
            },
            "version": {
                "major": 10,
                "minor": 0,
                "micro": 11,
                "string": "10.0.11",
                "edition": "nexus"
            }
        }
    }
}
```

closes #263

### CODE REVIEW

**Comment by labkode** [comment]
@refs only add the license and I'm happy to merge :)

**Comment by refs** [comment]
@labkode 👍 🎖

**Comment by butonic** [comment]
Fixes https://github.com/cs3org/reva/issues/256

**Pull request merged**
