### PR TITLE
[build-deps] Update CODEOWNERS

### PR DESCRIPTION
**Pull request by micbar**
@labkode @ishank011

I think it makes sense to also add the oc team as codeowners for ocdav and ocs.

### CODE REVIEW

**Comment by labkode** [comment]
@micbar please add ishank and me as well

**Comment by micbar** [comment]
> @micbar please add ishank and me as well

You are owners of `*` which means everything

**Comment by labkode** [comment]
@micbar it doesn't work like that, `*` won't create a review from either me or Ishank

**Comment by micbar** [comment]
ok, done.

**Comment by micbar** [comment]
let us "Squash and merge" we do not need 2 commits for such a small change 😄

**Review by labkode — APPROVED** [review]

**Pull request merged**
