### PR TITLE
[tests-only] Bump core commit id for tests (master)

### PR DESCRIPTION
**Pull request by saw-jan**
Bump core commit id for tests

Part of
https://github.com/owncloud/QA/issues/785

### CODE REVIEW

**Comment by kulmann** [comment]
Wondering if this recurring task still makes sense. I was under the impression that the reva `master` doesn't run `drone` at all anymore. Who can confirm? @micbar ?

**Comment by saw-jan** [comment]
> Wondering if this recurring task still makes sense. I was under the impression that the reva `master` doesn't run `drone` at all anymore. Who can confirm? @micbar ?

Yeah, heard the same. Looks like the drone is still running for PRs to master. 
Should we continue bumping commit-id till the drone is dropped or cease to do so?

CC @phil-davis

**Comment by micbar** [comment]
please rebase. the CI has changed on master.

**Comment by phil-davis** [comment]
> please rebase. the CI has changed on master.

rebased - I will look at what needs to be deleted from expected-failures files etc.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
