### PR TITLE
Sharing fix

### PR DESCRIPTION
**Pull request by ishank011**

### CODE REVIEW

**Comment by labkode** [comment]
@ishank011 @butonic this change still doesn't make the CI test happy

**Comment by ishank011** [comment]
@labkode https://github.com/labkode/reva/pull/183#issuecomment-834161878

**Comment by pascalwengerter** [comment]
@ishank011 what's the timeline for merging this? Just stumbled upon the fact that link-share navigation is broken in the current `web` due to the paths being too limited ;) I'll need those changes to close https://github.com/owncloud/web/pull/5122

**Comment by ishank011** [comment]
@pascalwengerter the tests need to be updated, else the CI would break. Please refer https://github.com/labkode/reva/pull/183#issuecomment-842285293. @butonic or @phil-davis will be able to give a better estimate

**Comment by ishank011** [comment]
Closing this, continuing the discussion at https://github.com/labkode/reva/pull/183

**Pull request closed without merging**
