### PR TITLE
[tests-only] Remove local api test that are present in core and covered by expected to fail file

### PR DESCRIPTION
**Pull request by SwikritiT**
We have `local-api-tests` that demonstrates different bugs but those tests are not necessary as they are already covered by `tests present in core` and they are linked in `expected-to-fail file`. If some tests starts to fail or pass we'll know. This PR removes the unnecessary `local-tests`. 

Part of : https://github.com/owncloud/ocis/issues/2313

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: this is similar to https://github.com/owncloud/ocis/pull/2341

**Review by phil-davis — APPROVED** [review]

**Comment by SwikritiT** [comment]
> Note: this is similar to [owncloud/ocis#2341](https://github.com/owncloud/ocis/pull/2341)
> 
> After this, we just have some previews "bug-demo" tests locally here. We will sort those out so that the core tests get run, and then remove those from this repo as well.

We don't have the `previews bug-demo` tests here. They were the same as the tests in `core` and were present in the expected to fail file so I removed them from this repo. We need to review the  `previews bug-demo` tests present in ocis repo.

**Comment by SwikritiT** [comment]
> > Note: this is similar to [owncloud/ocis#2341](https://github.com/owncloud/ocis/pull/2341)
> > After this, we just have some previews "bug-demo" tests locally here. We will sort those out so that the core tests get run, and then remove those from this repo as well.
> 
> We don't have the `previews bug-demo` tests here. They were the same as the tests in `core` and were present in the expected to fail file so I removed them from this repo. We need to review the `previews bug-demo` tests present in ocis repo.


> > Note: this is similar to [owncloud/ocis#2341](https://github.com/owncloud/ocis/pull/2341)
> > After this, we just have some previews "bug-demo" tests locally here. We will sort those out so that the core tests get run, and then remove those from this repo as well.
> 
> We don't have the `previews bug-demo` tests here. They were the same as the tests in `core` and were present in the expected to fail file so I removed them from this repo. We need to review the `previews bug-demo` tests present in ocis repo.

Sorry , I got confused. I have restored the file. We need to review that file in both repos.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@ishank011 these are an easy-win delete of "duplicate" scenarios already covered in core tests. So this can be merged.

I have https://github.com/owncloud/core/pull/39092 in progress to sort out the previews tests in core. Tomorrow we will make another PR here to adjust those and remove the "local" previews tests here.

**Review by ishank011 — APPROVED** [review]

**Pull request merged**
