### PR TITLE
Delete public share

### PR DESCRIPTION
**Pull request by C0rby**
I extracted the read and write db methods into methods to reduce duplication and implemented the RevokePublicShareMethod.
@PVince81, can you have a look. Did I miss something for deleting?

Implements delete for https://github.com/owncloud/ocis-reva/issues/293.

### CODE REVIEW

**Comment by PVince81** [comment]
is this working already ?
I thought we might need to make changes in shares.go as I saw separate implementation for user shares and public share.
If that works already, nice.

Can you enable the matching API tests and verify that they pass ?

**Comment by C0rby** [comment]
I'll try the acceptance tests.

I didn't try my implementation yet to be honest.

**Comment by refs** [comment]
> I'll try the acceptance tests.
> 
> I didn't try my implementation yet to be honest.

The implementation is 👍 , but curious to see oc10 end to end tests, since deleting a share actually works as in: the vuejs component deletes the element from the view, but the request essentially fail.

We can try this tomorrow @C0rby

**Comment by C0rby** [comment]
Ok so there was some missing stuff. Now I implemented everything to make public link shares work and ran the acceptance tests.
All but one run successfully. The one that fails is about deleting a share of a file, which was renamed. I'll create a ticket for that.

**Comment by C0rby** [comment]
Ok so there was some missing stuff. Now I implemented everything to make public link shares work and ran the acceptance tests.
All but one run successfully. The one that fails is about deleting a share of a file, which was renamed. I'll create a ticket for that.

**Comment by C0rby** [comment]
This PR won't update for some reason.
Will close and reopen

**Pull request closed without merging**
