### PR TITLE
[tests-only] [full-ci] Run API tests from ocis repo (master)

### PR DESCRIPTION
**Pull request by phil-davis**
1) Bump CORE_COMMITID for API tests (get it up-to-date and passing first
2) run the API tests out of the owncloud/ocis repo

The API test code and feature files was moved to `owncloud/ocis` in PR https://github.com/owncloud/ocis/pull/5280

The original API test code in `owncloud/core` will no longer be guaranteed to support reva/ocis special settings etc. So we will be better to run the API test code that is in `owncloud/ocis`

Note: this has also been done in edge PR #3591

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by saw-jan** [comment]
Need to bring back `--remote` related code in the `run.sh`

**Comment by phil-davis** [comment]
> Need to bring back `--remote` related code in the `run.sh`

Hmmm - this stuff passed in reva edge branch, which has `--remote` mentioned in `Makefile`. I suppose that it is ignored (does nothing special any more), but it passes anyway.

I pushed a commit to remove `--remote` here, just to see what happens. I suspect that it will still fail.

**Comment by phil-davis** [comment]
> I pushed a commit to remove `--remote` here, just to see what happens. I suspect that it will still fail.

It passed. That's good :)

**Review by individual-it — DISMISSED** [review]

**Comment by phil-davis** [comment]
@labkode @glpatcern @gmgigi96 I have touched some file that needs special approval (maybe `Makefile` is the one)

Please review/approve.

**Comment by phil-davis** [comment]
@labkode @glpatcern @gmgigi96 ping

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
@labkode @glpatcern @gmgigi96 ping again - please review/approve/merge.

**Review by vascoguita — APPROVED** [review]

**Review by glpatcern — APPROVED** [review]
Apologies for the delay, we reviewed this with @vascoguita as we are also evolving the CI. Hopefully if we get drone fully functional as well we should be all good.

**Comment by phil-davis** [comment]
Note: this change did not change the tests that are run, or how many pipelines are run etc.
It just changed the source of the test scenarios and test code, because we moved all that into the `owncloud/ocis` repository.

**Comment by vascoguita** [comment]
@phil-davis Is it possible to use only `owncloud/ocis`?
I see that the `virtualViews` test uses `owncloud/ocis` now but `s3ngIntegrationTests` and the `ocisIntegrationTests` are still using `owncloud/core`.

**Comment by phil-davis** [comment]
> Is it possible to use only `owncloud/ocis`?

I am not sure what you mean. `.drone.star `cloneApiTestReposStep()` has:
```
"git clone -b $APITESTS_BRANCH --single-branch --no-tags https://github.com/owncloud/ocis.git /drone/src/tmp/testrunner",
```

The feature files and test code are cloned from `owncloud/ocis` for all the acceptance test pipelines.

**Comment by vascoguita** [comment]
Indeed, everything moved to `owncloud/ocis`. Please ignore my comment

**Pull request merged**
