### PR TITLE
Add support for a custom CodiMD mimetype

### PR DESCRIPTION
**Pull request by glpatcern**
This is for now hardcoded, still have to parse the appropriate config section.

### CODE REVIEW

**Review by ishank011 — COMMENTED** [review]
@glpatcern can we instead call RegisterMime from the init method of appprovider? Something like adding `mime.RegisterMime(".zmd", "application/compressed-markdown")` in

https://github.com/cs3org/reva/blob/6b143c297df7ccb57ca2df822a835a6e65a74a4f/internal/grpc/services/appprovider/appprovider.go#L46-L48

**Comment by glpatcern** [comment]
Makes sense - and surely we can read the config there in appprovider once it's ready.

**Comment by ishank011** [comment]
Well if we can add it through appprovider, the whole process becomes much simpler 😁 

I'd still like to implement the functionality to pass configs to packages, but that can be put on the backburner for now. I'll create a PR to this branch to enable reading this config.

**Comment by glpatcern** [comment]
Yes, I agree that passing configs to packages should be done as a back-burner task.

At the same time, with this PR we're saying "new mime types can be defined in the context of the appprovider only", which is fair enough for now but in general that statement could be proven wrong.

**Review by ishank011 — APPROVED** [review]

**Comment by ishank011** [comment]
@glpatcern agreed!

**Pull request merged**
