### PR TITLE
Remove integration tests

### PR DESCRIPTION
**Pull request by phil-davis**
to investigate issue #942 

1) remove owncloud API integration tests
2) remove litmus test pipelines
3) touch README a few times to keep triggering CI

### CODE REVIEW

**Comment by phil-davis** [comment]
https://cloud.drone.io/cs3org/reva/1743/3/1
The very first "clone" step failed with `No space left on device`

**Comment by phil-davis** [comment]
`build-only` pipeline often passes. But this run https://cloud.drone.io/cs3org/reva/1746 failed on the very first clone.

**Comment by labkode** [comment]
@phil-davis so there is something going bananas ... let me try to resync the project with Drone.

**Comment by phil-davis** [comment]
Failed again here: https://cloud.drone.io/cs3org/reva/1754/1/3

**Comment by labkode** [comment]
@phil-davis what about https://github.com/cs3org/reva/issues/948?

**Comment by phil-davis** [comment]
https://discourse.drone.io/t/no-space-left-on-cloud-drone-io/7650
From ashwilliams1 "This issue has been resolved."

**Pull request closed without merging**
