### PR TITLE
[tests-only][full-ci] bump latest ocis commit on master

### PR DESCRIPTION
**Pull request by PrajwolAmatya**
This PR bumps the latest ocis commit id
part of https://github.com/owncloud/QA/issues/815

### CODE REVIEW

**Review by individual-it — DISMISSED** [review]

**Comment by phil-davis** [comment]
Assigned myself just so that I can easily find this PR

**Comment by phil-davis** [comment]
Does the `master` CI still use https://github.com/cs3org/reva/blob/master/.drone.env ?
Are we still keeping the commit id up-to-date in that file?

**Comment by PrajwolAmatya** [comment]
> Does the `master` CI still use https://github.com/cs3org/reva/blob/master/.drone.env ? Are we still keeping the commit id up-to-date in that file?

Sorry I missed to update the drone.env file to new commit id. It is now updated.

**Comment by grgprarup** [comment]
> Does the `master` CI still use https://github.com/cs3org/reva/blob/master/.drone.env ? Are we still keeping the commit id up-to-date in that file?

One pipeline of ocis-integration test and s3-integration tests run on the drone. A drone is using .drone.env commit id.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
