### PR TITLE
Add API key to Mentix GOCDB connector

### PR DESCRIPTION
**Pull request by Daniel-WWU-IT**
The PI (programmatic interface) of the GOCDB will soon require an API key; this PR adds the ability to configure this key in Mentix.

### CODE REVIEW

**Comment by Daniel-WWU-IT** [comment]
CI failing might be due to https://github.com/cs3org/reva/pull/1833, can't explain otherwise.

**Comment by labkode** [comment]
@Daniel-WWU-IT is Dockerfile.old expected?

**Comment by Daniel-WWU-IT** [comment]
Woops, no, I'll remove/ignore it. It's just there until the charts have been updated to match the new Dockerfile.

**Comment by Daniel-WWU-IT** [comment]
@labkode Removed the file.

**Review by labkode — APPROVED** [review]

**Pull request merged**
