### PR TITLE
Feature: Nextcloud storage driver

### PR DESCRIPTION
**Pull request by michielbdejong**
Fixes https://github.com/cs3org/reva/issues/1862.

### CODE REVIEW

**Comment by michielbdejong** [comment]
Ah, I see quite a few lint errors from Hound and also a few in `make lint`, will attend to them!

**Comment by michielbdejong** [comment]
Hm, CI shows:
` FAIL	github.com/cs3org/reva/pkg/storage/fs/nextcloud [build failed]`

**Comment by michielbdejong** [comment]
Combining https://github.com/michielbdejong/reva/blob/nextcloud-storage-driver/.drone.star#L23 with https://github.com/michielbdejong/reva/blob/nextcloud-storage-driver/.drone.star#L154, I *think* the way to reproduce this error locally would be `make ci`.

When I do that on Mac, I get a `library not found for -lcrt0.o` error instead. I think that was something to do with dynamic vs static binding. I'll try out what happens when I run `make ci` on Ubuntu.

**Comment by michielbdejong** [comment]
Testing this now on an Ubuntu VPS. First, seeing if I can get `make ci` to work in the main branch. Then I'll try in my branch.

**Comment by michielbdejong** [comment]
Ah, now I found something:
```
go test github.com/cs3org/reva/pkg/storage/fs/nextcloud
# github.com/cs3org/reva/pkg/storage/fs/nextcloud_test [github.com/cs3org/reva/pkg/storage/fs/nextcloud.test]
pkg/storage/fs/nextcloud/nextcloud_test.go:64:13: undefined: nextcloud.NewNextcloudStorageDriver
pkg/storage/fs/nextcloud/nextcloud_test.go:64:50: undefined: nextcloud.NextcloudStorageDriverConfig
FAIL	github.com/cs3org/reva/pkg/storage/fs/nextcloud [build failed]
FAIL
```

**Comment by michielbdejong** [comment]
@labkode can you review this when you have a moment, please?

**Comment by labkode** [comment]
Hi @michielbdejong this is a good starting point, we can merge this one and iteratively working on it.

**Review by labkode — APPROVED** [review]

**Review by labkode — APPROVED** [review]

**Pull request merged**
