### PR TITLE
add userid to username mapping to public shares

### PR DESCRIPTION
**Pull request by C0rby**
I missed some spots for public shares

### CODE REVIEW

**Review by kulmann — DISMISSED** [review]

**Review by butonic — DISMISSED** [review]

**Review by refs — DISMISSED** [review]

**Comment by refs** [comment]
Perhaps this needs to be rebased with `master`

**Comment by C0rby** [comment]
Hmm, well let's try. :thinking:

**Comment by C0rby** [comment]
Seems like we have random etag test failures again... :tada:

**Review by refs — APPROVED** [review]

**Review by kulmann — APPROVED** [review]

**Comment by ishank011** [comment]
@C0rby can you rebase?

**Comment by C0rby** [comment]
I'm closing this PR because this change was also implemented by https://github.com/cs3org/reva/pull/1451

**Pull request closed without merging**
