### PR TITLE
test: use empty array for ocs notifications api

### LINKED ISSUE #1805: Remove hardcoded notifications capability
Just found out that the [ownCloud web frontend](https://github.com/owncloud/web/) incorrectly checks for notifications since the notifications capability in Reva, for historical reasons and contrary to the behavior in other capability cases, returns an array with a `"disable"` string (https://github.com/cs3org/reva/blob/a8c61401b662d8e09175416c0556da8ef3ba8ed6/tests/oc-integration-tests/local/frontend.toml#L110). 

To make it consistent we shouldn't return anything here until Reva/oCIS is capable of handling notifications.

Glad to take care of this myself when the time comes but also don't want to cause a breaking change in the Semver for this minor nitpicky issue

### PR DESCRIPTION
**Pull request by labkode**
Fixes #1805  
@pascalwengerter

### CODE REVIEW

**Comment by labkode** [comment]
@pascalwengerter CI is happy, as soon as it gets approved by QA team I merge it.

**Comment by labkode** [comment]
Ping @phil-davis

**Comment by pascalwengerter** [comment]
Discussing the implemention of this with @refs right now, will update this as soon as we come to a conclusion

**Review by phil-davis — APPROVED** [review]
That's fine to change. We currently skip the test scenarios that test the notifications behavior - see mentions of `~@notifications-app-required` in `.drone.star`

If/when notifications start to be added/supported we can easily remove the skipping, and at that point some development effort will provide more than just an empty response.

**Comment by pascalwengerter** [comment]
Superseded by #1819 to get the behaviour we want for `web` and other `clients`

**Review by ishank011 — APPROVED** [review]

**Pull request merged**
