### PR TITLE
[Tests-Only] Run litmus CI for both owncloud and ocis storage

### PR DESCRIPTION
**Pull request by phil-davis**
Test both `ocis` and `owncloud` storage with litmus.

(after this is merged, I will then work on running the API tests with `ocis` storage as well as `owncloud` storage)

### CODE REVIEW

**Comment by phil-davis** [comment]
@butonic this PR runs litmus tests on both `owncloud` and `ocis` storage. `owncloud` passes (like it already did). `ocis` storage fails:

old webdav:
https://cloud.drone.io/cs3org/reva/2525/3/5
```
...
10. move_coll............. 
10. move_coll............. FAIL (collection COPY `/remote.php/webdav/litmus/mvdest/' to `/remote.php/webdav/litmus/mvdest2/', depth infinity: 500 Internal Server Error)

11. move_cleanup.......... 
11. move_cleanup.......... pass

12. finish................ 
12. finish................ pass
<- summary for `copymove': of 13 tests run: 12 passed, 1 failed. 92.3%
```

new webdav:
https://cloud.drone.io/cs3org/reva/2525/5/5
```
...
10. move_coll............. 
10. move_coll............. FAIL (collection COPY `/remote.php/dav/files/4c510ada-c86b-4815-8820-42cdf82c3d51/litmus/mvdest/' to `/remote.php/dav/files/4c510ada-c86b-4815-8820-42cdf82c3d51/litmus/mvdest2/', depth infinity: 500 Internal Server Error)

11. move_cleanup.......... 
11. move_cleanup.......... pass

12. finish................ 
12. finish................ pass
<- summary for `copymove': of 13 tests run: 12 passed, 1 failed. 92.3%
```

Is there a known issue with copying/moving a collection/folder?

**Comment by phil-davis** [comment]
I cherry-picked from PR #1177 into here - to demonstrate that litmus now passes for `ocis` storage.

**Comment by phil-davis** [comment]
Now litmus fails in a different way: https://cloud.drone.io/cs3org/reva/2566/3/5
```
13. propreplace........... 
13. propreplace........... FAIL (PROPPATCH on `/remote.php/webdav/litmus/prop2': 500 Internal Server Error)

14. propget............... 
14. propget............... FAIL (Property {http://example.com/neon/litmus/}prop9 had value value9, expected newvalue9)

15. propnullns............ 
15. propnullns............ pass

16. propget............... 
16. propget............... pass

17. propremoveset......... 
17. propremoveset......... FAIL (PROPPATCH remove then set)

18. propget............... 
18. propget............... FAIL (No value given for property {http://example.com/neon/litmus/}removeset)
```

This is after PR #1177 "fix ocis move" was merged.

**Comment by phil-davis** [comment]
PR #1179 fixed the fails. I rebased, so this should pass now.

**Comment by phil-davis** [comment]
@ishank011 CI  should pass here now - please review.

**Review by ishank011 — APPROVED** [review]

**Pull request merged**
