### PR TITLE
reduce logging output

### PR DESCRIPTION
**Pull request by C0rby**
Reduced log output. Some errors or warnings were logged multiple times or even unnecesarily. 

Now, there are probably a lot of places where logging is missing but these can be added when we touch those spots again.

### CODE REVIEW

**Comment by C0rby** [comment]
Similarly, should both the services and the gateway log stuff or only one of both? If the latter who should log? I'd say the service itself would make sense.

**Comment by C0rby** [comment]
I added error logging to the storage provider. It probably would make sense to have more logging in other places too but I propose to add those when we are working at those places.

**Comment by refs** [comment]
I find this approach better rather than having a wall of text. Adding logging when needed (if needed) is more beneficial 👍

**Comment by C0rby** [comment]
There are more things that can be done but I'm going to leave it at that to not make this PR any longer.

**Review by refs — APPROVED** [review]

**Review by rhafer — APPROVED** [review]

**Review by kobergj — APPROVED** [review]

**Pull request merged**
