### PR TITLE
fix wrong space editor permission

### PR DESCRIPTION
**Pull request by micbar**
# Description

A space editor should not have the permission to purge the trash bin.

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Various tests now fail, for example:
https://drone.owncloud.com/cs3org/reva/1697/12/6
```
Failed step: And as user "Brian" folder "/Shares/tmp" should contain a property "ocs:share-permissions" with value "15"
        Property "ocs:share-permissions" found with value "7", expected "#^15$#" or "#^15$#"
```

If this is the new requirement, then tests need adjusting. The "source" test scenarios are in ocis, so maybe the known-failing tests get added to expected-failures here with and issue raised in ocis. Then we adjust the test scenarios in ocis as we pull this code into ocis. Then we pull the updated ocis tests back into reva (and the expected-failures can be deleted)

**Comment by micbar** [comment]
@phil-davis There must be something wrong. That should not touch sharing at all.

**Review by kobergj — APPROVED** [review]
:+1: Good enough for me. Note that It won't affect existing space editors

**Comment by micbar** [comment]
Let's see, there were some code changes missing. Now it should work and pass the testsuite.

**Review by kobergj — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
