### PR TITLE
[tests-only] [full-ci] bump latest commit from ocis

### PR DESCRIPTION
**Pull request by PrajwolAmatya**
This PR bumps the latest commit id from ocis
part of https://github.com/owncloud/QA/issues/811

### CODE REVIEW

**Review by phil-davis — DISMISSED** [review]
LGTM if CI passes

**Comment by saw-jan** [comment]
Need to update [cs3org/behat](https://github.com/cs3org/behat/blob/main/vendor-bin/behat/composer.json) to have the json-assert library

**Comment by grgprarup** [comment]
> Need to update [cs3org/behat](https://github.com/cs3org/behat/blob/main/vendor-bin/behat/composer.json) to have the json-assert library

@vascoguita @phil-davis

**Comment by PrajwolAmatya** [comment]
@vascoguita In the test for `asserting JSON` a package `"helmich/phpunit-json-assert": "^3.4"` is required, so this [cs3org/behat](https://github.com/cs3org/behat/blob/main/vendor-bin/behat/composer.json) needs to be updated with that package.

**Comment by vascoguita** [comment]
I'm no longer a member of the CERNBox team, so I don't maintain the CI anymore but I suggest you create a PR to cs3org/behat. Once accepted it will build and push the docker image automatically and the CI will update the behat image in use.

**Comment by phil-davis** [comment]
I will make a PR in a few minutes...

**Comment by phil-davis** [comment]
PR https://github.com/cs3org/behat/pull/1

@vascoguita who should I ping to get that approved?

**Comment by phil-davis** [comment]
https://github.com/cs3org/behat/pull/1 has been merged. I requested to rerun the CI jobs. Let's see what happens...

**Review by phil-davis — DISMISSED** [review]

**Comment by vascoguita** [comment]
> PR [cs3org/behat#1](https://github.com/cs3org/behat/pull/1)
> 
> @vascoguita who should I ping to get that approved?

I would ask @labkode

**Comment by phil-davis** [comment]
> I would ask @labkode

It has already been approved and merged, thanks.

I am running CI again to get an updated result. Hopefully the merged changes to dependencies "magically" appear in the CI.

**Comment by vascoguita** [comment]
> > I would ask @labkode
> 
> It has already been approved and merged, thanks.
> 
> I am running CI again to get an updated result. Hopefully the merged changes to dependencies "magically" appear in the CI.

I have bad news for you. It is using the old cached image. I'll ask my old colleagues to clean up the runners and we try again.
The good news is that the new behat image was successfully built and published: https://hub.docker.com/repository/docker/cs3org/behat/general

**Pull request merged**
